#!/usr/bin/bash

SHOW_ALT='no'
ORIGINAL_PHONETICS='no'
SHOW_ORIGINAL='no'
PROMPT_MSG='no'
TARGET='en'
WIDTH=400
HEIGHT=200
Y_OFFSET=50
X_OFFSET=0
eval $(xdotool getmouselocation --shell)

if [ ! -z "$1" ];then
  TEXT="$@"
else
  TEXT="$(xsel -o)"
fi
T_CMD="trans --show-alternatives $SHOW_ALT\
  --show-original-phonetics $ORIGINAL_PHONETICS\
  --show-original $SHOW_ORIGINAL\
  --show-prompt-message $PROMPT_MSG\
  --target $TARGET
"

TR_TXT=$($T_CMD "$TEXT" |
  awk 'gsub(/\[24m/,"</word>") gsub(/\[4m/,"<word>") gsub(/\[1m/,"<word>") gsub(/\[22m/,"</word>") gsub(/\[22m/,"</word>") gsub("$","<br>")'
)
awk -v payload="$TR_TXT" '{ sub("landing",payload,$0); print $0}' template.html > result.html 

yad --html --uri=result.html --no-buttons --geometry=500x200+$(( $X+$X_OFFSET ))+$(( $Y+$X_OFFSET ))
